// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm8mFZnPCf1bW3Ryyf38QG53IV0ZWycpo',
    appId: '1:879333288681:web:c3d05e281d7db6acc4de78',
    messagingSenderId: '879333288681',
    projectId: 'brie-app-462f5',
    authDomain: 'brie-app-462f5.firebaseapp.com',
    storageBucket: 'brie-app-462f5.firebasestorage.app',
    measurementId: 'G-LR90FDQVQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByJjOZl8XCUMe9dzt2fHrJvd_aurd6bPw',
    appId: '1:879333288681:android:5259fe5e72b2d74ec4de78',
    messagingSenderId: '879333288681',
    projectId: 'brie-app-462f5',
    storageBucket: 'brie-app-462f5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwMgoFd_87fibLd8caMdEUftClZnwX6Ys',
    appId: '1:879333288681:ios:69138b8770c51360c4de78',
    messagingSenderId: '879333288681',
    projectId: 'brie-app-462f5',
    storageBucket: 'brie-app-462f5.firebasestorage.app',
    iosBundleId: 'com.example.brie',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwMgoFd_87fibLd8caMdEUftClZnwX6Ys',
    appId: '1:879333288681:ios:69138b8770c51360c4de78',
    messagingSenderId: '879333288681',
    projectId: 'brie-app-462f5',
    storageBucket: 'brie-app-462f5.firebasestorage.app',
    iosBundleId: 'com.example.brie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm8mFZnPCf1bW3Ryyf38QG53IV0ZWycpo',
    appId: '1:879333288681:web:02ba93612d319e4fc4de78',
    messagingSenderId: '879333288681',
    projectId: 'brie-app-462f5',
    authDomain: 'brie-app-462f5.firebaseapp.com',
    storageBucket: 'brie-app-462f5.firebasestorage.app',
    measurementId: 'G-DLWH125BQR',
  );
}
